name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare-yarn-cache-ubuntu:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: ubuntu-latest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare-yarn-cache-ubuntu

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build
      - name: run eslint
        run: yarn lint
      - name: run prettier
        run: yarn lint:prettier:ci

  yarn-validate:
    name: Validate Yarn dependencies and constraints
    runs-on: ubuntu-latest
    needs: prepare-yarn-cache-ubuntu

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: 'Check for unmet constraints (fix w/ "yarn constraints --fix")'
        run: yarn constraints
      - name: 'Check for duplicate dependencies (fix w/ "yarn depude")'
        run: yarn dedupe --check

  test:
    uses: ./.github/workflows/test.yml
    needs: prepare-yarn-cache-ubuntu
    with:
      os: ubuntu-latest
